repository_menu_controller: onbase_documents
no_automatic_routes: true
parents:
  accession:
    name: onbase_documents
    cardinality: zero_to_many
  event:
    name: onbase_documents
    cardinality: zero_to_many
  archival_object:
    name: onbase_documents
    cardinality: zero_to_many
  resource:
    name: onbase_documents
    cardinality: zero_to_many
